import fs from 'fs';
import * as S from './node_modules/satellite.mjs';
const text = fs.readFileSync('data/tles/real/glonass.txt','utf8');
const lines = text.split('\n').map(l=>l.trim()).filter(l => /^1 [0-9]/.test(l) || /^2 [0-9]/.test(l));
const l1 = lines[0], l2 = lines[1];
console.log('l1:', l1);
console.log('l2:', l2);
const sat = S.twoline2satrec(l1, l2);
console.log('sat.error:', sat.error, 'sat.a:', sat.a, 'sat.jdsatepoch:', sat.jdsatepoch);
const now = new Date();
console.log('now:', now.toISOString());
const j = S.jday(now);
console.log('jday(now):', j);
const m = (j - sat.jdsatepoch) * 1440;
console.log('m:', m);
const r1 = S.sgp4(sat, m);
console.log('sgp4(m):', r1.error, r1.position);
const r2 = S.propagate(sat, now);
console.log('propagate(now):', r2.error, r2.position);
